name: CI pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permission:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: build
        run: echo "hello"

  test:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: test
        run: whoami